### ISSUE TITLE
Unable to upload files in Drive subfolder

### ISSUE THREAD

**Issue by lbologna** [HumanBrainProject/ebrains-drive#12]
Hello,

We are getting a 403 error when we try to upload a file to a subfolder of a Collab's Drive, while the upload works well when uploading to the root folder.

Here's the code that works:

```
import ebrains_drive
COLLAB_URL = 'https://wiki.ebrains.eu/bin/view/Collabs/hhnb-registeredmodels/'
COLLAB_DIR = ''
client = ebrains_drive.connect(username="lbologna", password="XXXXXX")
repo = client.repos.get_repo_by_url(COLLAB_URL)
seafdir = repo.get_dir('/' + COLLAB_DIR)
uploaded_file = seafdir.upload_local_file("./test_LLB")
```

The same code does not work anymore when we set the following:

`COLLAB_DIR = 'hhnb_wf_model'
`

Any clue on this?

Thank you.

**Comment by appukuttan-shailesh** [comment]
Hey @lbologna , 
Just coincidentally I had opened a PR this morning to fix this isssue.
See here:
https://github.com/HumanBrainProject/ebrains-drive/pull/11

**Comment by rcsm17** [comment]
> Hey @lbologna , Just coincidentally I had opened a PR this morning to fix this isssue. See here: #11

Hi @appukuttan-shailesh, the fix you provided resolves this issue. Thank you !

**Comment by Cracky5457** [comment]
A new release 0.3.0 including shailesh changed is available on `pip install ebrains-drive`

Thanks for reporting and fixing it.

Axel

**Comment by appukuttan-shailesh** [comment]
Thanks Axel for the quick action.
I have tested the new release, and it seems to be working fine :+1:
